### ISSUE TITLE
Add ability to define columns in JSON file

### ISSUE THREAD

**Issue by rippinrobr** [rippinrobr/csv-to#46]
For tables like the retrosheet game_log table, it would be nice if there's a way for me to define the column names and data types so they have meaningful names.

Requirements
1. Need to be able to easily create this file, probably use TOML or YAML
2. have structure like:
    ```
    - columns:
         - col_name: type
         - col_name: type
         - col_name: type
    ```
3. Start off with only having support for the `--one-table` option

The goal here is to have a way to define the column names, at the least, for files that have no headers
